### ISSUE TITLE
[Bug]: Decoration placer will not open

### ISSUE THREAD

**Issue by kikoboy11** [The-Fireplace/Simply-Caterpillar#17]
### Mod Version

1.19.3

### What mod loader(s) are you seeing the problem on?

Fabric

### Problem Description

Cannot access or use the Decoration Placer at all on my server.

**Comment by Daniel-Mendes** [comment]
Yes the mod is broken on server.

**Comment by Daniel-Mendes** [comment]
Fixed with release of 8.0.2
